development:
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: coinfi-rails_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: coinfi-rails_production
